import { Command } from "commander";
import { resolve } from "node:path";
import { existsSync, mkdirSync } from "node:fs";
import { input, select } from "@inquirer/prompts";
import { getLibraryPath, loadConfig } from "../lib/config.js";
import {
  createNewFrontmatter,
  writeSnippetFile,
} from "../lib/frontmatter.js";
import { uniqueSlug } from "../lib/slug.js";
import { readClipboard } from "../lib/clipboard.js";
import { EXIT_CODES } from "../types/index.js";
import { updateAndEmbed } from "../lib/qmd.js";
import { fmt } from "../lib/format.js";
import ora from "ora";
import { enrichSnippet, setProviderOverride, setDebugMode } from "../lib/llm.js";
import type { LlmProviderName } from "../types/index.js";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { writeFileSync, readFileSync, unlinkSync } from "node:fs";

export const addCommand = new Command("add")
  .description("Add a new snippet")
  .option("-t, --type <type>", "Snippet type (directory)")
  .option("-l, --lang <language>", "Programming language")
  .option("--tags <tags>", "Comma-separated tags")
  .option("--title <title>", "Snippet title")
  .option("--from-clipboard", "Create snippet from clipboard content")
  .option("--content <content>", "Snippet content (non-interactive)")
  .option("--provider <provider>", "LLM provider override (ollama, gemini, claude, openai, auto)")
  .option("--debug", "Log LLM provider commands and responses")
  .action(async (opts) => {
    if (opts.debug) setDebugMode(true);
    if (opts.provider) {
      setProviderOverride(opts.provider as LlmProviderName);
    }
    const config = loadConfig();
    const libPath = getLibraryPath(config);

    if (!existsSync(libPath)) {
      console.error(
        "Snippet library not initialized. Run `snip init` first.",
      );
      process.exit(EXIT_CODES.CONFIG_ERROR);
    }

    let title = opts.title || "";
    let language = opts.lang || "";
    let tags: string[] = opts.tags ? opts.tags.split(",").map((t: string) => t.trim()) : [];
    let type = opts.type || config.defaultType;
    let content = opts.content || "";

    if (opts.fromClipboard) {
      content = await readClipboard();
      if (!content.trim()) {
        console.error("Clipboard is empty.");
        process.exit(EXIT_CODES.GENERAL_ERROR);
      }

      // Title will be generated by LLM enrichment if not provided
    }

    // Interactive mode if no content provided
    if (!content) {
      if (!title) {
        title = await input({ message: "Title:" });
      }

      if (!language) {
        language = await input({
          message: "Language (e.g., bash, python, prompt):",
        });
      }

      if (tags.length === 0) {
        const tagsInput = await input({
          message: "Tags (comma-separated):",
        });
        tags = tagsInput
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean);
      }

      if (config.types.length > 1 && !opts.type) {
        type = await select({
          message: "Type:",
          choices: config.types.map((t) => ({ value: t, name: t })),
        });
      }

      // Open editor for content
      const editor = config.editor || process.env.EDITOR || "vi";
      const tmpFile = resolve(
        tmpdir(),
        `snip-${Date.now()}.${language || "md"}`,
      );
      const fenceHint = language
        ? `\`\`\`${language}\n\n\`\`\``
        : "```\n\n```";
      writeFileSync(
        tmpFile,
        `# ${title}\n\n${fenceHint}\n`,
        "utf-8",
      );

      const [editorCmd, ...editorArgs] = editor.split(/\s+/);
      const result = spawnSync(editorCmd, [...editorArgs, tmpFile], {
        stdio: "inherit",
      });

      if (result.status !== 0) {
        console.error("Editor exited with error.");
        process.exit(EXIT_CODES.GENERAL_ERROR);
      }

      content = readFileSync(tmpFile, "utf-8");
      unlinkSync(tmpFile);
    }

    // Build initial frontmatter
    const frontmatter = createNewFrontmatter({
      title,
      language,
      tags,
      type,
    });

    // LLM enrichment: fill in missing metadata BEFORE writing the file
    const spinner = ora("Enriching snippet…").start();
    const enriched = await enrichSnippet(frontmatter, content);
    spinner.stop();
    if (Object.keys(enriched).length > 0) {
      if (enriched.title && !opts.title) title = enriched.title;
      if (enriched.language && !language) language = enriched.language;
      if (enriched.tags?.length && !tags.length) tags = enriched.tags;
    }

    // Fallback title if none was provided and enrichment did not set one
    if (!title) {
      const timestamp = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
      title = `untitled-${timestamp}`;
    }

    // Wrap content in code fence after enrichment so language is available
    if (!content.includes("```") && language) {
      content = `\n\`\`\`${language}\n${content}\n\`\`\`\n`;
    }

    // If enrichment detected prompt language, switch type to prompts
    if (
      enriched.language === "prompt" &&
      !opts.type &&
      type !== "prompts" &&
      config.types.includes("prompts")
    ) {
      type = "prompts";
    }

    // Merge enriched data into frontmatter
    const finalFm = {
      ...frontmatter,
      ...enriched,
      title,
      language,
      tags,
      type,
    };

    // Ensure type directory exists
    const typeDir = resolve(libPath, type);
    mkdirSync(typeDir, { recursive: true });

    // Generate slug and file path using the (possibly enriched) title
    const slug = uniqueSlug(title, typeDir);
    const filePath = resolve(typeDir, `${slug}.md`);

    writeSnippetFile(filePath, finalFm, content);

    console.log(`${fmt.green("Created:")} ${filePath}`);
    console.log(`  ${fmt.dim("Title:")} ${title}`);
    if (language) console.log(`  ${fmt.dim("Language:")} ${language}`);
    if (tags.length) console.log(`  ${fmt.dim("Tags:")} ${fmt.cyan(tags.join(", "))}`);
    if (enriched.description) console.log(`  ${fmt.dim("Description:")} ${enriched.description}`);
    if (enriched.aliases?.length) console.log(`  ${fmt.dim("Aliases:")} ${enriched.aliases.join(", ")}`);
    if (enriched.language && !opts.lang) console.log(`  ${fmt.dim("Auto-detected language:")} ${enriched.language}`);
    if (enriched.tags?.length && !opts.tags) console.log(`  ${fmt.dim("Suggested tags:")} ${enriched.tags.join(", ")}`);

    // qmd post-hook: update index
    await updateAndEmbed();
  });
