import { Command } from "commander";
import { homedir } from "node:os";
import { resolve } from "node:path";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

interface CommandInfo {
  name: string;
  description: string;
  options: { flags: string; description: string; long: string }[];
  takesSnippetArg: boolean;
}

function introspectProgram(program: Command): CommandInfo[] {
  const commands: CommandInfo[] = [];

  for (const cmd of program.commands) {
    const name = cmd.name();
    const description = cmd.description() || "";

    const options = cmd.options.map((opt) => ({
      flags: opt.flags,
      description: opt.description || "",
      long: opt.long || "",
    }));

    // Commands that take a snippet name as first arg
    const snippetCommands = [
      "show",
      "copy",
      "edit",
      "rm",
      "run",
      "link",
      "rename",
    ];
    const takesSnippetArg = snippetCommands.includes(name);

    commands.push({ name, description, options, takesSnippetArg });
  }

  return commands;
}

function generateZshCompletions(commands: CommandInfo[]): string {
  const commandList = commands
    .map((c) => `    '${c.name}:${c.description.replace(/'/g, "'\\''")}'`)
    .join("\n");

  const caseBranches = commands
    .map((c) => {
      if (c.takesSnippetArg) {
        return `        ${c.name})\n          _snip_snippets\n          ;;`;
      }
      if (c.options.length === 0) return null;
      const optLines = c.options
        .map((o) => {
          const long = o.long || o.flags.split(",").pop()?.trim() || "";
          return `            '${long}[${o.description.replace(/'/g, "'\\''")}]'`;
        })
        .join(" \\\n");
      return `        ${c.name})\n          _arguments \\\n${optLines}\n          ;;`;
    })
    .filter(Boolean)
    .join("\n");

  return `#compdef snip
# snip CLI completions — generated by: snip install completions
# Regenerate after adding commands: snip install completions zsh

_snip_snippets() {
  local snippets
  snippets=(\${(f)"$(snip list --json 2>/dev/null | node -e "
    let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{
      try{JSON.parse(d).forEach(s=>console.log(s.slug+':'+s.title))}catch{}
    })")"})
  _describe 'snippet' snippets
}

_snip() {
  local -a commands
  commands=(
${commandList}
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
${caseBranches}
        install)
          local -a integrations
          integrations=('completions:Install shell completions' 'alfred:Install Alfred workflow' 'obsidian:Set up Obsidian vault')
          _describe 'integration' integrations
          ;;
      esac
      ;;
  esac
}

_snip "$@"
`;
}

function generateBashCompletions(commands: CommandInfo[]): string {
  const commandNames = commands.map((c) => c.name).join(" ");

  const snippetCmds = commands
    .filter((c) => c.takesSnippetArg)
    .map((c) => c.name)
    .join("|");

  const optionCases = commands
    .filter((c) => !c.takesSnippetArg && c.options.length > 0)
    .map((c) => {
      const opts = c.options.map((o) => o.long || o.flags.split(",").pop()?.trim() || "").join(" ");
      return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${opts}" -- "\${cur}") )\n      return 0\n      ;;`;
    })
    .join("\n");

  return `# snip CLI completions — generated by: snip install completions
# Regenerate after adding commands: snip install completions bash

_snip_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  commands="${commandNames}"

  case "\${COMP_WORDS[1]}" in
    ${snippetCmds})
      local snippets
      snippets="$(snip list --json 2>/dev/null | node -e "
        let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{
          try{JSON.parse(d).forEach(s=>console.log(s.slug))}catch{}
        })")"
      COMPREPLY=( $(compgen -W "\${snippets}" -- "\${cur}") )
      return 0
      ;;
    install)
      COMPREPLY=( $(compgen -W "completions alfred obsidian" -- "\${cur}") )
      return 0
      ;;
${optionCases}
    *)
      ;;
  esac

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
  fi

  return 0
}

complete -F _snip_completions snip
`;
}

function generateFishCompletions(commands: CommandInfo[]): string {
  const lines: string[] = [
    "# snip CLI completions — generated by: snip install completions",
    "# Regenerate after adding commands: snip install completions fish",
    "",
    "# Disable file completions by default",
    "complete -c snip -f",
    "",
    "# Helper function to get snippet slugs",
    "function __snip_slugs",
    '  snip list --json 2>/dev/null | node -e "',
    "    let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{",
    "      try{JSON.parse(d).forEach(s=>console.log(s.slug+'\\\\t'+s.title))}catch{}",
    '    })"',
    "end",
    "",
    "# Commands",
  ];

  for (const cmd of commands) {
    lines.push(
      `complete -c snip -n '__fish_use_subcommand' -a ${cmd.name} -d '${cmd.description.replace(/'/g, "'\\''")}'`,
    );
  }

  lines.push("");

  // Snippet name completions
  const snippetCmds = commands
    .filter((c) => c.takesSnippetArg)
    .map((c) => c.name)
    .join(" ");
  lines.push("# Snippet name completions");
  lines.push(
    `for cmd in ${snippetCmds}`,
    `  complete -c snip -n "__fish_seen_subcommand_from $cmd" -a '(__snip_slugs)'`,
    "end",
    "",
  );

  // Option completions per command
  for (const cmd of commands) {
    if (cmd.options.length === 0) continue;
    lines.push(`# ${cmd.name} options`);
    for (const opt of cmd.options) {
      const long = (opt.long || "").replace(/^--/, "");
      if (!long) continue;
      lines.push(
        `complete -c snip -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long} -d '${opt.description.replace(/'/g, "'\\''")}'`,
      );
    }
  }

  // Install subcommands
  lines.push("");
  lines.push("# install subcommands");
  lines.push(
    "complete -c snip -n '__fish_seen_subcommand_from install' -a completions -d 'Install shell completions'",
    "complete -c snip -n '__fish_seen_subcommand_from install' -a alfred -d 'Install Alfred workflow'",
    "complete -c snip -n '__fish_seen_subcommand_from install' -a obsidian -d 'Set up Obsidian vault'",
  );

  lines.push("");
  return lines.join("\n");
}

function detectShell(): string {
  const shell = process.env.SHELL || "";
  if (shell.includes("zsh")) return "zsh";
  if (shell.includes("fish")) return "fish";
  return "bash";
}

const COMPLETIONS_DIR = ".zsh/completions";
const FPATH_LINE = `fpath=(~/${COMPLETIONS_DIR} $fpath)`;
const COMPINIT_LINE = "autoload -Uz compinit && compinit";

function getCompletionPath(shell: string): string {
  switch (shell) {
    case "zsh":
      return resolve(homedir(), COMPLETIONS_DIR, "_snip");
    case "fish":
      return resolve(homedir(), ".config", "fish", "completions", "snip.fish");
    case "bash":
      return resolve(
        homedir(),
        ".local",
        "share",
        "bash-completion",
        "completions",
        "snip",
      );
    default:
      return "";
  }
}

function ensureZshrcSetup(): { injected: boolean; message: string } {
  const zshrc = resolve(homedir(), ".zshrc");
  if (!existsSync(zshrc)) {
    return { injected: false, message: "No ~/.zshrc found. Create one and add:\n\n  " + FPATH_LINE + "\n  " + COMPINIT_LINE };
  }

  const content = readFileSync(zshrc, "utf-8");
  const lines = content.split("\n");

  const hasFpath = lines.some((l) => l.includes(COMPLETIONS_DIR) && l.includes("fpath"));
  const hasCompinit = lines.some((l) => l.includes("compinit"));

  if (hasFpath && hasCompinit) {
    return { injected: false, message: "~/.zshrc already configured." };
  }

  // Build the snippet to inject
  const snippet: string[] = [];
  snippet.push("# snip CLI completions");
  if (!hasFpath) snippet.push(FPATH_LINE);
  if (!hasCompinit) snippet.push(COMPINIT_LINE);

  // Find a safe insertion point: look for the first fpath or compinit line,
  // then walk backwards past any comment block that belongs to it
  let targetIdx = -1;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (!trimmed.startsWith("#") && (trimmed.includes("fpath") || trimmed.includes("compinit"))) {
      targetIdx = i;
      break;
    }
  }

  if (targetIdx >= 0) {
    // Walk backwards past comments that belong to this line
    let insertIdx = targetIdx;
    while (insertIdx > 0 && lines[insertIdx - 1].trim().startsWith("#")) {
      insertIdx--;
    }
    // Insert before the comment block, with a blank line separator
    lines.splice(insertIdx, 0, ...snippet, "");
  } else {
    // No fpath/compinit found — append to end
    lines.push("", ...snippet);
  }

  writeFileSync(zshrc, lines.join("\n"), "utf-8");
  return { injected: true, message: "Updated ~/.zshrc with fpath and compinit." };
}

function getSourceInstruction(shell: string, path: string, zshSetupMsg?: string): string {
  switch (shell) {
    case "zsh": {
      const setup = zshSetupMsg ? `${zshSetupMsg}\n\n` : "";
      return (
        `Completions installed to: ${path}\n\n` +
        setup +
        `Open a new terminal tab, or run:\n\n` +
        `  rm -f ~/.zcompdump* && source ~/.zshrc`
      );
    }
    case "fish":
      return (
        `Completions installed to: ${path}\n\n` +
        `Fish will pick them up automatically. Restart your shell or run:\n\n` +
        `  source ${path}`
      );
    case "bash":
      return (
        `Completions installed to: ${path}\n\n` +
        `Add to ~/.bashrc if not already:\n\n` +
        `  [ -f ${path} ] && source ${path}\n\n` +
        `Then restart your shell or run: source ~/.bashrc`
      );
    default:
      return "";
  }
}

export function createInstallCommand(program: Command): Command {
  return new Command("install")
    .description("Install integrations and extensions")
    .argument(
      "<integration>",
      "Integration to install (completions, alfred, obsidian)",
    )
    .argument("[shell]", "Shell type for completions (bash, zsh, fish)")
    .action(async (integration: string, shell?: string) => {
      switch (integration) {
        case "completions": {
          const targetShell = shell || detectShell();

          if (!["bash", "zsh", "fish"].includes(targetShell)) {
            console.error(
              `Unsupported shell: ${targetShell}. Supported: bash, zsh, fish`,
            );
            process.exit(1);
          }

          const commands = introspectProgram(program);

          let script: string;
          switch (targetShell) {
            case "zsh":
              script = generateZshCompletions(commands);
              break;
            case "fish":
              script = generateFishCompletions(commands);
              break;
            default:
              script = generateBashCompletions(commands);
              break;
          }

          const outPath = getCompletionPath(targetShell);
          const outDir = resolve(outPath, "..");
          mkdirSync(outDir, { recursive: true });
          writeFileSync(outPath, script, "utf-8");

          let zshSetupMsg: string | undefined;
          if (targetShell === "zsh") {
            const result = ensureZshrcSetup();
            zshSetupMsg = result.message;
          }

          console.log(`Installed ${targetShell} completions for snip.`);
          console.log();
          console.log(getSourceInstruction(targetShell, outPath, zshSetupMsg));
          break;
        }

        case "alfred":
          console.error(
            "Alfred workflow installation coming soon. See: snip search --json",
          );
          process.exit(1);
          break;

        case "obsidian":
          console.error("Obsidian vault setup coming soon.");
          process.exit(1);
          break;

        default:
          console.error(
            `Unknown integration: ${integration}. Available: completions, alfred, obsidian`,
          );
          process.exit(1);
      }
    });
}
