import { Command } from "commander";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, copyFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { loadConfig, getLibraryPath } from "../lib/config.js";
import { isObsidianInstalled, isObsidianCliAvailable, getVaultName } from "../lib/obsidian.js";

interface CommandInfo {
  name: string;
  description: string;
  options: { flags: string; description: string; long: string }[];
  takesSnippetArg: boolean;
}

function introspectProgram(program: Command): CommandInfo[] {
  const commands: CommandInfo[] = [];

  for (const cmd of program.commands) {
    const name = cmd.name();
    const description = cmd.description() || "";

    const options = cmd.options.map((opt) => ({
      flags: opt.flags,
      description: opt.description || "",
      long: opt.long || "",
    }));

    // Detect commands that take a snippet name/slug as first arg
    const firstArg = cmd.registeredArguments[0];
    const argDesc = firstArg?.description || "";
    const takesSnippetArg = argDesc.toLowerCase().includes("snippet name")
      || argDesc.toLowerCase().includes("snippet slug");

    commands.push({ name, description, options, takesSnippetArg });
  }

  return commands;
}

function generateZshCompletions(commands: CommandInfo[]): string {
  const commandList = commands
    .map((c) => `    '${c.name}:${c.description.replace(/'/g, "'\\''")}'`)
    .join("\n");

  const caseBranches = commands
    .map((c) => {
      if (c.takesSnippetArg) {
        return `        ${c.name})\n          _snip_snippets\n          ;;`;
      }
      if (c.options.length === 0) return null;
      const optLines = c.options
        .map((o) => {
          const long = o.long || o.flags.split(",").pop()?.trim() || "";
          return `            '${long}[${o.description.replace(/'/g, "'\\''")}]'`;
        })
        .join(" \\\n");
      return `        ${c.name})\n          _arguments \\\n${optLines}\n          ;;`;
    })
    .filter(Boolean)
    .join("\n");

  return `#compdef snip
# snip CLI (https://github.com/jtsternberg/snippets-cli) completions
# Generated by: snip install completions
# Regenerate after adding commands: snip install completions zsh

_snip_snippets() {
  local snippets
  snippets=(\${(f)"$(snip list --json 2>/dev/null | node -e "
    let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{
      try{JSON.parse(d).forEach(s=>console.log(s.slug+':'+s.title))}catch{}
    })")"})
  _describe 'snippet' snippets
}

_snip() {
  local -a commands
  commands=(
${commandList}
  )

  _arguments -C \\
    '1:command:->command' \\
    '*::arg:->args'

  case $state in
    command)
      _describe 'command' commands
      ;;
    args)
      case $words[1] in
${caseBranches}
        install)
          local -a integrations
          integrations=('completions:Install shell completions' 'alfred:Install Alfred workflow' 'obsidian:Set up Obsidian vault')
          _describe 'integration' integrations
          ;;
      esac
      ;;
  esac
}

_snip "$@"
`;
}

function generateBashCompletions(commands: CommandInfo[]): string {
  const commandNames = commands.map((c) => c.name).join(" ");

  const snippetCmds = commands
    .filter((c) => c.takesSnippetArg)
    .map((c) => c.name)
    .join("|");

  const optionCases = commands
    .filter((c) => !c.takesSnippetArg && c.options.length > 0)
    .map((c) => {
      const opts = c.options.map((o) => o.long || o.flags.split(",").pop()?.trim() || "").join(" ");
      return `    ${c.name})\n      COMPREPLY=( $(compgen -W "${opts}" -- "\${cur}") )\n      return 0\n      ;;`;
    })
    .join("\n");

  return `# snip CLI (https://github.com/jtsternberg/snippets-cli) completions
# Generated by: snip install completions
# Regenerate after adding commands: snip install completions bash

_snip_completions() {
  local cur prev commands
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  commands="${commandNames}"

  case "\${COMP_WORDS[1]}" in
    ${snippetCmds})
      local snippets
      snippets="$(snip list --json 2>/dev/null | node -e "
        let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{
          try{JSON.parse(d).forEach(s=>console.log(s.slug))}catch{}
        })")"
      COMPREPLY=( $(compgen -W "\${snippets}" -- "\${cur}") )
      return 0
      ;;
    install)
      COMPREPLY=( $(compgen -W "completions alfred obsidian" -- "\${cur}") )
      return 0
      ;;
${optionCases}
    *)
      ;;
  esac

  if [[ \${COMP_CWORD} -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
  fi

  return 0
}

complete -F _snip_completions snip
`;
}

function generateFishCompletions(commands: CommandInfo[]): string {
  const lines: string[] = [
    "# snip CLI (https://github.com/jtsternberg/snippets-cli) completions",
    "# Generated by: snip install completions",
    "# Regenerate after adding commands: snip install completions fish",
    "",
    "# Disable file completions by default",
    "complete -c snip -f",
    "",
    "# Helper function to get snippet slugs",
    "function __snip_slugs",
    '  snip list --json 2>/dev/null | node -e "',
    "    let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{",
    "      try{JSON.parse(d).forEach(s=>console.log(s.slug+'\\\\t'+s.title))}catch{}",
    '    })"',
    "end",
    "",
    "# Commands",
  ];

  for (const cmd of commands) {
    lines.push(
      `complete -c snip -n '__fish_use_subcommand' -a ${cmd.name} -d '${cmd.description.replace(/'/g, "'\\''")}'`,
    );
  }

  lines.push("");

  // Snippet name completions
  const snippetCmds = commands
    .filter((c) => c.takesSnippetArg)
    .map((c) => c.name)
    .join(" ");
  lines.push("# Snippet name completions");
  lines.push(
    `for cmd in ${snippetCmds}`,
    `  complete -c snip -n "__fish_seen_subcommand_from $cmd" -a '(__snip_slugs)'`,
    "end",
    "",
  );

  // Option completions per command
  for (const cmd of commands) {
    if (cmd.options.length === 0) continue;
    lines.push(`# ${cmd.name} options`);
    for (const opt of cmd.options) {
      const long = (opt.long || "").replace(/^--/, "");
      if (!long) continue;
      lines.push(
        `complete -c snip -n '__fish_seen_subcommand_from ${cmd.name}' -l ${long} -d '${opt.description.replace(/'/g, "'\\''")}'`,
      );
    }
  }

  // Install subcommands
  lines.push("");
  lines.push("# install subcommands");
  lines.push(
    "complete -c snip -n '__fish_seen_subcommand_from install' -a completions -d 'Install shell completions'",
    "complete -c snip -n '__fish_seen_subcommand_from install' -a alfred -d 'Install Alfred workflow'",
    "complete -c snip -n '__fish_seen_subcommand_from install' -a obsidian -d 'Set up Obsidian vault'",
  );

  lines.push("");
  return lines.join("\n");
}

export function detectShell(): string {
  const shell = process.env.SHELL || "";
  if (shell.includes("zsh")) return "zsh";
  if (shell.includes("fish")) return "fish";
  return "bash";
}

const COMPLETIONS_DIR = ".zsh/completions";
const FPATH_LINE = `fpath=(~/${COMPLETIONS_DIR} $fpath)`;
const COMPINIT_LINE = "autoload -Uz compinit && compinit";

export function getCompletionPath(shell: string): string {
  switch (shell) {
    case "zsh":
      return resolve(homedir(), COMPLETIONS_DIR, "_snip");
    case "fish":
      return resolve(homedir(), ".config", "fish", "completions", "snip.fish");
    case "bash":
      return resolve(
        homedir(),
        ".local",
        "share",
        "bash-completion",
        "completions",
        "snip",
      );
    default:
      return "";
  }
}

function ensureZshrcSetup(): { injected: boolean; message: string } {
  const zshrc = resolve(homedir(), ".zshrc");
  if (!existsSync(zshrc)) {
    return { injected: false, message: "No ~/.zshrc found. Create one and add:\n\n  " + FPATH_LINE + "\n  " + COMPINIT_LINE };
  }

  const content = readFileSync(zshrc, "utf-8");
  const lines = content.split("\n");

  const hasFpath = lines.some((l) => l.includes(COMPLETIONS_DIR) && l.includes("fpath"));
  const hasCompinit = lines.some((l) => l.includes("compinit"));

  if (hasFpath && hasCompinit) {
    return { injected: false, message: "~/.zshrc already configured." };
  }

  // Build the snippet to inject
  const snippet: string[] = [];
  snippet.push("# snip CLI (https://github.com/jtsternberg/snippets-cli) completions");
  if (!hasFpath) snippet.push(FPATH_LINE);
  if (!hasCompinit) snippet.push(COMPINIT_LINE);

  // Find a safe insertion point: look for the first fpath or compinit line,
  // then walk backwards past any comment block that belongs to it
  let targetIdx = -1;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (!trimmed.startsWith("#") && (trimmed.includes("fpath") || trimmed.includes("compinit"))) {
      targetIdx = i;
      break;
    }
  }

  if (targetIdx >= 0) {
    // Walk backwards past comments that belong to this line
    let insertIdx = targetIdx;
    while (insertIdx > 0 && lines[insertIdx - 1].trim().startsWith("#")) {
      insertIdx--;
    }
    // Insert before the comment block, with a blank line separator
    lines.splice(insertIdx, 0, ...snippet, "");
  } else {
    // No fpath/compinit found — append to end
    lines.push("", ...snippet);
  }

  writeFileSync(zshrc, lines.join("\n"), "utf-8");
  return { injected: true, message: "Updated ~/.zshrc with fpath and compinit." };
}

function getSourceInstruction(shell: string, path: string, zshSetupMsg?: string): string {
  switch (shell) {
    case "zsh": {
      const setup = zshSetupMsg ? `${zshSetupMsg}\n\n` : "";
      return (
        `Completions installed to: ${path}\n\n` +
        setup +
        `Open a new terminal tab, or run:\n\n` +
        `  rm -f ~/.zcompdump* && source ~/.zshrc`
      );
    }
    case "fish":
      return (
        `Completions installed to: ${path}\n\n` +
        `Fish will pick them up automatically. Restart your shell or run:\n\n` +
        `  source ${path}`
      );
    case "bash":
      return (
        `Completions installed to: ${path}\n\n` +
        `Add to ~/.bashrc if not already:\n\n` +
        `  [ -f ${path} ] && source ${path}\n\n` +
        `Then restart your shell or run: source ~/.bashrc`
      );
    default:
      return "";
  }
}

function getSnipPath(): string {
  try {
    return execSync("which snip", { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] }).trim();
  } catch {
    return "snip";
  }
}

function getAlfredPrefsPath(): string {
  // Read Alfred's configured sync folder from macOS defaults
  // Try Alfred 5 first, then fall back to Alfred 3/4
  const domains = [
    "com.runningwithcrayons.Alfred-Preferences-3",
    "com.runningwithcrayons.Alfred-Preferences",
  ];

  for (const domain of domains) {
    try {
      const syncfolder = execSync(`defaults read ${domain} syncfolder`, {
        encoding: "utf-8",
        stdio: ["pipe", "pipe", "pipe"],
      }).trim();

      const resolved = syncfolder.replace(/^~\//, homedir() + "/");
      const prefs = resolve(resolved, "Alfred.alfredpreferences");
      if (existsSync(prefs)) return prefs;
    } catch {
      // Domain not found, try next
    }
  }

  // Fallback: standard location
  const fallback = resolve(
    homedir(),
    "Library",
    "Application Support",
    "Alfred",
    "Alfred.alfredpreferences",
  );
  if (existsSync(fallback)) return fallback;

  return "";
}

const BUNDLE_ID = "com.jtsternberg.snip-search";

function findExistingWorkflow(workflowsDir: string): string | null {
  if (!existsSync(workflowsDir)) return null;

  for (const entry of readdirSync(workflowsDir)) {
    if (!entry.startsWith("user.workflow.")) continue;
    const plistPath = resolve(workflowsDir, entry, "info.plist");
    if (!existsSync(plistPath)) continue;

    try {
      const bid = execSync(
        `/usr/libexec/PlistBuddy -c 'Print :bundleid' "${plistPath}"`,
        { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] },
      ).trim();
      if (bid === BUNDLE_ID) {
        return resolve(workflowsDir, entry);
      }
    } catch {
      // Skip unreadable plists
    }
  }

  return null;
}

export function generateInfoPlist(snipBin: string, maxResults: number): string {
  // Shared preamble for all Alfred scripts:
  // - Ensures common binary locations are on PATH
  // - Sets SNIP_BIN to the detected path at install time unless the user has
  //   already set it in Alfred's Workflow Environment Variables (Preferences →
  //   Workflows → [workflow] → Configure Workflow → Environment Variables).
  // Using ${VAR:=default} via the : builtin safely handles paths with spaces.
  const preamble = [
    `export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"`,
    `: "\${SNIP_BIN:=${snipBin}}"`,
  ].join("\n");

  const searchScript = [
    preamble,
    `"$SNIP_BIN" search "{query}" --json -n ${maxResults}`,
  ].join("\n");
  const captureScript = [
    preamble,
    `echo -n "$1" | pbcopy`,
    `output=$("$SNIP_BIN" add --from-clipboard 2>&1)`,
    `filepath=$(echo "$output" | grep "^Created:" | sed 's/Created: //')`,
    `echo -n "$filepath"`,
  ].join("\n");
  const keywordCaptureScript = [
    preamble,
    `output=$("$SNIP_BIN" add --from-clipboard 2>&1)`,
    `filepath=$(echo "$output" | grep "^Created:" | sed 's/Created: //')`,
    `echo -n "$filepath"`,
  ].join("\n");

  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>bundleid</key>
	<string>com.jtsternberg.snip-search</string>
	<key>category</key>
	<string>Productivity</string>
	<key>connections</key>
	<dict>
		<key>keyword-capture</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>keyword-capture-script</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
		<key>keyword-capture-script</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>capture-openfile</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
		<key>capture-trigger</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>capture-script</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
		<key>capture-openfile</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>capture-notify</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
		<key>capture-script</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>capture-openfile</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
		<key>script-filter</key>
		<array>
			<dict>
				<key>destinationuid</key>
				<string>paste-action</string>
				<key>modifiers</key>
				<integer>0</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
			<dict>
				<key>destinationuid</key>
				<string>copy-action</string>
				<key>modifiers</key>
				<integer>1048576</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
			<dict>
				<key>destinationuid</key>
				<string>editor-action</string>
				<key>modifiers</key>
				<integer>524288</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
			<dict>
				<key>destinationuid</key>
				<string>finder-action</string>
				<key>modifiers</key>
				<integer>262144</integer>
				<key>modifiersubtext</key>
				<string></string>
				<key>vitoclose</key>
				<false/>
			</dict>
		</array>
	</dict>
	<key>createdby</key>
	<string>Justin Sternberg</string>
	<key>description</key>
	<string>Search code snippets with snip CLI</string>
	<key>disabled</key>
	<false/>
	<key>name</key>
	<string>Snip Search</string>
	<key>objects</key>
	<array>
		<dict>
			<key>config</key>
			<dict>
				<key>autopaste</key>
				<true/>
				<key>clipboardtext</key>
				<string>{query}</string>
				<key>transient</key>
				<false/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.output.clipboard</string>
			<key>uid</key>
			<string>paste-action</string>
			<key>version</key>
			<integer>3</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>autopaste</key>
				<false/>
				<key>clipboardtext</key>
				<string>{query}</string>
				<key>transient</key>
				<false/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.output.clipboard</string>
			<key>uid</key>
			<string>copy-action</string>
			<key>version</key>
			<integer>3</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>openwith</key>
				<string></string>
				<key>sourcefile</key>
				<string>{query}</string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.openfile</string>
			<key>uid</key>
			<string>editor-action</string>
			<key>version</key>
			<integer>3</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>sourcefile</key>
				<string>{query}</string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.revealfile</string>
			<key>uid</key>
			<string>finder-action</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>alfredfiltersresults</key>
				<false/>
				<key>alfredfiltersresultsmatchmode</key>
				<integer>0</integer>
				<key>argumenttreatemptyqueryasnil</key>
				<false/>
				<key>argumenttrimmode</key>
				<integer>0</integer>
				<key>argumenttype</key>
				<integer>0</integer>
				<key>escaping</key>
				<integer>102</integer>
				<key>keyword</key>
				<string>snip</string>
				<key>queuedelaycustom</key>
				<integer>3</integer>
				<key>queuedelayimmediatelyinitially</key>
				<false/>
				<key>queuedelaymode</key>
				<integer>0</integer>
				<key>queuemode</key>
				<integer>1</integer>
				<key>runningsubtext</key>
				<string>Searching snippets…</string>
				<key>script</key>
				<string>${escapeXml(searchScript)}</string>
				<key>scriptargtype</key>
				<integer>0</integer>
				<key>scriptfile</key>
				<string></string>
				<key>subtext</key>
				<string>Search your snippet library</string>
				<key>title</key>
				<string>Snip: Search Snippets</string>
				<key>type</key>
				<integer>5</integer>
				<key>withspace</key>
				<true/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.input.scriptfilter</string>
			<key>uid</key>
			<string>script-filter</string>
			<key>version</key>
			<integer>3</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>acceptsfiles</key>
				<false/>
				<key>acceptsmulti</key>
				<integer>0</integer>
				<key>acceptstext</key>
				<true/>
				<key>acceptsurls</key>
				<false/>
				<key>name</key>
				<string>Snip: Save Snippet</string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.trigger.universalaction</string>
			<key>uid</key>
			<string>capture-trigger</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>concurrently</key>
				<false/>
				<key>escaping</key>
				<integer>102</integer>
				<key>script</key>
				<string>${escapeXml(captureScript)}</string>
				<key>scriptargtype</key>
				<integer>1</integer>
				<key>scriptfile</key>
				<string></string>
				<key>type</key>
				<integer>5</integer>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.script</string>
			<key>uid</key>
			<string>capture-script</string>
			<key>version</key>
			<integer>2</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>openwith</key>
				<string></string>
				<key>sourcefile</key>
				<string>{query}</string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.openfile</string>
			<key>uid</key>
			<string>capture-openfile</string>
			<key>version</key>
			<integer>3</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>lastpathcomponent</key>
				<false/>
				<key>onlyshowifquerypopulated</key>
				<false/>
				<key>removeextension</key>
				<false/>
				<key>text</key>
				<string>{query}</string>
				<key>title</key>
				<string>Snip: Snippet Saved</string>
			</dict>
			<key>type</key>
			<string>alfred.workflow.output.notification</string>
			<key>uid</key>
			<string>capture-notify</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>argumenttype</key>
				<integer>2</integer>
				<key>keyword</key>
				<string>snipsaveclipboard</string>
				<key>subtext</key>
				<string>Save clipboard contents as a snippet</string>
				<key>text</key>
				<string>Snip: Save Snippet from Clipboard</string>
				<key>withspace</key>
				<false/>
			</dict>
			<key>type</key>
			<string>alfred.workflow.input.keyword</string>
			<key>uid</key>
			<string>keyword-capture</string>
			<key>version</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>config</key>
			<dict>
				<key>concurrently</key>
				<false/>
				<key>escaping</key>
				<integer>102</integer>
				<key>script</key>
				<string>${escapeXml(keywordCaptureScript)}</string>
				<key>scriptargtype</key>
				<integer>1</integer>
				<key>scriptfile</key>
				<string></string>
				<key>type</key>
				<integer>5</integer>
			</dict>
			<key>type</key>
			<string>alfred.workflow.action.script</string>
			<key>uid</key>
			<string>keyword-capture-script</string>
			<key>version</key>
			<integer>2</integer>
		</dict>
	</array>
	<key>readme</key>
	<string></string>
	<key>uidata</key>
	<dict>
		<key>paste-action</key>
		<dict>
			<key>xpos</key>
			<real>400</real>
			<key>ypos</key>
			<real>50</real>
		</dict>
		<key>copy-action</key>
		<dict>
			<key>xpos</key>
			<real>465</real>
			<key>ypos</key>
			<real>180</real>
		</dict>
		<key>editor-action</key>
		<dict>
			<key>xpos</key>
			<real>455</real>
			<key>ypos</key>
			<real>310</real>
		</dict>
		<key>finder-action</key>
		<dict>
			<key>xpos</key>
			<real>295</real>
			<key>ypos</key>
			<real>375</real>
		</dict>
		<key>script-filter</key>
		<dict>
			<key>xpos</key>
			<real>100</real>
			<key>ypos</key>
			<real>150</real>
		</dict>
		<key>capture-trigger</key>
		<dict>
			<key>xpos</key>
			<real>100</real>
			<key>ypos</key>
			<real>500</real>
		</dict>
		<key>capture-script</key>
		<dict>
			<key>xpos</key>
			<real>350</real>
			<key>ypos</key>
			<real>500</real>
		</dict>
		<key>capture-openfile</key>
		<dict>
			<key>xpos</key>
			<real>600</real>
			<key>ypos</key>
			<real>500</real>
		</dict>
		<key>capture-notify</key>
		<dict>
			<key>xpos</key>
			<real>850</real>
			<key>ypos</key>
			<real>500</real>
		</dict>
		<key>keyword-capture</key>
		<dict>
			<key>xpos</key>
			<real>100</real>
			<key>ypos</key>
			<real>650</real>
		</dict>
		<key>keyword-capture-script</key>
		<dict>
			<key>xpos</key>
			<real>350</real>
			<key>ypos</key>
			<real>650</real>
		</dict>
	</dict>
	<key>userconfigurationconfig</key>
	<array/>
	<key>version</key>
	<string>1.0.0</string>
	<key>webaddress</key>
	<string></string>
</dict>
</plist>`;
}

// Bundled Alfred workflow icon (256×256 PNG).
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const WORKFLOW_ICON_PATH = resolve(__dirname, "../assets/alfred-icon.png");

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function installAlfredWorkflow(): void {
  const prefsPath = getAlfredPrefsPath();

  if (!prefsPath) {
    console.error(
      "Alfred preferences not found. Is Alfred installed?\n" +
      "Checked macOS defaults and ~/Library/Application Support/Alfred/",
    );
    process.exit(1);
  }

  const workflowsDir = resolve(prefsPath, "workflows");
  const snipBin = getSnipPath();
  const config = loadConfig();
  const maxResults = config.alfred?.maxResults ?? 20;

  // Find existing workflow by bundle ID, or create new UUID-based directory
  let workflowDir = findExistingWorkflow(workflowsDir);
  if (workflowDir) {
    console.log("Updating existing Snip Search workflow...");
  } else {
    const uuid = crypto.randomUUID().toUpperCase();
    workflowDir = resolve(workflowsDir, `user.workflow.${uuid}`);
  }
  mkdirSync(workflowDir, { recursive: true });

  const plist = generateInfoPlist(snipBin, maxResults);
  writeFileSync(resolve(workflowDir, "info.plist"), plist, "utf-8");

  // Copy the workflow icon (non-fatal if it fails)
  try {
    copyFileSync(WORKFLOW_ICON_PATH, resolve(workflowDir, "icon.png"));
  } catch {
    console.warn("Warning: Could not write workflow icon");
  }

  console.log("Installed Alfred workflow: Snip Search");
  console.log();
  console.log(`  Keyword: snip`);
  console.log(`  Location: ${workflowDir}`);
  console.log();
  console.log("Actions:");
  console.log("  Enter        Copy snippet to clipboard");
  console.log("  Cmd+Enter    Copy snippet to clipboard");
  console.log("  Alt+Enter    Open snippet file (default app)");
  console.log("  Ctrl+Enter   Reveal snippet in Finder");
  console.log("  Space        Quick Look preview");
  console.log();
  console.log("Tip: Set max results with: snip config set alfred.maxResults 30");
  console.log("Tip: Override snip binary with SNIP_BIN in Alfred's Workflow Environment Variables");
  console.log("       (Alfred Preferences → Workflows → Snip Search → Configure Workflow → Environment Variables)");
}

export async function installShellCompletions(program: Command, shell?: string): Promise<void> {
  const targetShell = shell || detectShell();

  if (!["bash", "zsh", "fish"].includes(targetShell)) {
    throw new Error(`Unsupported shell: ${targetShell}. Supported: bash, zsh, fish`);
  }

  const commands = introspectProgram(program);

  let script: string;
  switch (targetShell) {
    case "zsh":
      script = generateZshCompletions(commands);
      break;
    case "fish":
      script = generateFishCompletions(commands);
      break;
    default:
      script = generateBashCompletions(commands);
      break;
  }

  const outPath = getCompletionPath(targetShell);
  const outDir = resolve(outPath, "..");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, script, "utf-8");

  let zshSetupMsg: string | undefined;
  if (targetShell === "zsh") {
    const result = ensureZshrcSetup();
    zshSetupMsg = result.message;
  }

  console.log(`Installed ${targetShell} completions for snip.`);
  console.log();
  console.log(getSourceInstruction(targetShell, outPath, zshSetupMsg));
}

function installObsidian(): void {
  if (!isObsidianInstalled()) {
    console.error(
      "Obsidian not found. Install it from https://obsidian.md",
    );
    process.exit(1);
  }

  const config = loadConfig();
  const libraryPath = getLibraryPath(config);

  if (!existsSync(libraryPath)) {
    console.error("Snippet library not initialized. Run `snip init` first.");
    process.exit(1);
  }

  const hasCli = isObsidianCliAvailable();
  const vaultName = hasCli ? getVaultName(libraryPath) : null;
  let step = 1;

  console.log("Obsidian Setup Guide");
  console.log("====================");
  console.log();
  console.log(`Snippet library: ${libraryPath}`);
  console.log();

  if (vaultName) {
    console.log(`Opening vault "${vaultName}"...`);
    execSync(`open -a Obsidian "${libraryPath}"`);
    console.log();
  } else {
    console.log(`Step ${step++}: Open your snippet library as a vault`);
    console.log("  1. Open Obsidian");
    console.log("  2. Click \"Open another vault\" (vault icon in bottom-left)");
    console.log("  3. Click \"Open folder as vault\"");
    console.log(`  4. Select: ${libraryPath}`);
    console.log();
  }

  if (!hasCli) {
    console.log(`Step ${step++}: Enable the Obsidian CLI`);
    console.log("  Settings → General → Command line interface → Enable");
    console.log("  Then follow on-screen instructions to add it to your PATH.");
    console.log();
  }

  console.log(`Step ${step++}: Recommended settings`);
  console.log('  - Settings → Files & Links → Use [[Wikilinks]] → Enable');
  console.log('  - Settings → Files & Links → Default location for new notes → "In the folder specified below"');
  console.log('  - Set the folder to your default snippet type (e.g. "snippets")');
  console.log();
  console.log("Recommended community plugins:");
  console.log("  - Dataview — query snippets by frontmatter fields");
  console.log("  - Tag Wrangler — manage and rename tags");
  console.log("  - Templater — create snippet templates");

  if (hasCli) {
    const vaultFlag = vaultName ? ` vault="${vaultName}"` : "";
    console.log();
    console.log("Obsidian CLI commands for your snippets:");
    console.log(`  obsidian search query=<term>${vaultFlag}`);
    console.log(`  obsidian tags counts${vaultFlag}`);
    console.log(`  obsidian backlinks file=<name>${vaultFlag}`);
    console.log(`  obsidian orphans${vaultFlag}`);
    console.log(`  obsidian unresolved${vaultFlag}`);
  }
}

export function createInstallCommand(program: Command): Command {
  return new Command("install")
    .description("Install integrations and extensions")
    .argument(
      "<integration>",
      "Integration to install (completions, alfred, obsidian)",
    )
    .argument("[shell]", "Shell type for completions (bash, zsh, fish)")
    .action(async (integration: string, shell?: string) => {
      switch (integration) {
        case "completions": {
          try {
            await installShellCompletions(program, shell);
          } catch (err) {
            console.error(err instanceof Error ? err.message : String(err));
            process.exit(1);
          }
          break;
        }

        case "alfred":
          installAlfredWorkflow();
          break;

        case "obsidian":
          installObsidian();
          break;

        default:
          console.error(
            `Unknown integration: ${integration}. Available: completions, alfred, obsidian`,
          );
          process.exit(1);
      }
    });
}
